# Generated by Django 3.1.12 on 2021-06-25 16:04

import api.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My Collection', max_length=100)),
                ('description', models.CharField(blank=True, default='', max_length=1000)),
                ('is_archived', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=api.models.upload_image_name, validators=[api.models.validate_image, django.core.validators.validate_image_file_extension])),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('is_archived', models.BooleanField(blank=True, default=False)),
                ('video', models.FileField(blank=True, null=True, upload_to=api.models.upload_video_name, validators=[api.models.validate_video, django.core.validators.FileExtensionValidator(['mp4', 'mov', 'wmv', 'avi', ' AVCHD', 'FLV', 'MKV', 'WEBM'])])),
                ('transcript', models.URLField(blank=True, null=True)),
                ('summarization', models.JSONField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('audioText', models.FileField(blank=True, null=True, upload_to=api.models.upload_video_audioText_name)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.collection')),
            ],
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('is_archived', models.BooleanField(blank=True, default=False)),
                ('audio', models.FileField(upload_to=api.models.upload_audio_name)),
                ('transcript', models.URLField(blank=True, null=True)),
                ('summarization', models.JSONField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('audioText', models.FileField(blank=True, null=True, upload_to=api.models.upload_video_audioText_name)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.collection')),
            ],
        ),
    ]
