# Generated by Django 3.1.12 on 2021-06-17 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.collection'),
        ),
    ]
