# Generated by Django 3.1.12 on 2021-06-18 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210618_0449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='collection',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.collection'),
        ),
        migrations.AlterField(
            model_name='video',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
