# Generated by Django 3.1.10 on 2021-06-14 22:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='collection',
            name='cover_image',
            field=models.FileField(upload_to='image/%y'),
        ),
    ]
