# Generated by Django 3.1.10 on 2021-06-14 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210614_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='cover_image',
            field=models.FileField(blank=True, upload_to='image/%y'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='description',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
