# Generated by Django 3.1.10 on 2021-06-14 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210614_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='cover_image',
            field=models.FileField(null=True, upload_to='image/%y'),
        ),
    ]
