// social login
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";

// colllections
export const UPDATE_PERCENTAGE = "UPDATE_PERCENTAGE";
export const LOADING_COLLECTIONS = "LOADING_COLLECTIONS";
export const LOAD_COLLECTIONS_SUCCESS = "LOAD_COLLECTIONS_SUCCESS";
export const LOAD_COLLECTIONS_FAILURE = "LOAD_COLLECTIONS_FAILURE";
export const CREATING_COLLECTION = "CREATING_COLLECTION";
export const CREATE_COLLECTION_SUCCESS = "CREATE_COLLECTION_SUCCESS";
export const CREATE_COLLECTION_FAILURE = "CREATE_COLLECTION_FAILURE";
export const UPDATE_COLLECTION_SUCCESS = "UPDATE_COLLECTION_SUCCESS";
export const UPDATE_COLLECTION_FAILURE = "UPDATE_COLLECTION_FAILURE";
export const DELETING_COLLECTION = "DELETING_COLLECTION";
export const DELETE_COLLECTION_SUCCESS = "DELETE_COLLECTION_SUCCESS";
export const DELETE_COLLECTION_FAILURE = "DELETE_COLLECTION_FAILURE";
export const SELECT_COLLECTION = "SELECT_COLLECTION";
