// social login
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";

// colllections
export const UPDATE_PERCENTAGE = "UPDATE_PERCENTAGE";
export const LOADING_COLLECTIONS = "LOADING_COLLECTIONS";
export const LOAD_COLLECTIONS_SUCCESS = "LOAD_COLLECTIONS_SUCCESS";
export const LOAD_COLLECTIONS_FAILURE = "LOAD_COLLECTIONS_FAILURE";
export const CREATING_COLLECTION = "CREATING_COLLECTION";
export const CREATE_COLLECTION_SUCCESS = "CREATE_COLLECTION_SUCCESS";
export const CREATE_COLLECTION_FAILURE = "CREATE_COLLECTION_FAILURE";
export const UPDATE_COLLECTION_SUCCESS = "UPDATE_COLLECTION_SUCCESS";
export const UPDATE_COLLECTION_FAILURE = "UPDATE_COLLECTION_FAILURE";
export const DELETING_COLLECTION = "DELETING_COLLECTION";
export const DELETE_COLLECTION_SUCCESS = "DELETE_COLLECTION_SUCCESS";
export const DELETE_COLLECTION_FAILURE = "DELETE_COLLECTION_FAILURE";
export const SELECT_COLLECTION = "SELECT_COLLECTION";

// videos
export const LOADING_VIDEOS = "LOADING_VIDEOS";
export const LOAD_VIDEOS_SUCCESS = "LOAD_VIDEOS_SUCCESS";
export const LOAD_VIDEOS_FAILURE = "LOAD_VIDEOS_FAILURE";
export const CREATING_VIDEO = "CREATING_VIDEO";
export const CREATE_VIDEO_SUCCESS = "CREATE_VIDEO_SUCCESS";
export const CREATE_VIDEO_FAILURE = "CREATE_VIDEO_FAILURE";
export const UPDATE_VIDEO_SUCCESS = "UPDATE_VIDEO_SUCCESS";
export const UPDATE_VIDEO_FAILURE = "UPDATE_VIDEO_FAILURE";
export const DELETING_VIDEOS = "DELETING_VIDEOS";
export const DELETE_VIDEO_SUCCESS = "DELETE_VIDEO_SUCCESS";
export const DELETE_VIDEO_FAILURE = "DELETE_VIDEO_FAILURE";
export const CHANGE_VIDEO_SUMMARY_SUCCESS = "CHANGE_VIDEO_SUMMARY_SUCCESS";
export const CHANGE_VIDEO_SUMMARY_FAILURE = "CHANGE_VIDEO_SUMMARY_FAILURE";
export const RESET_VIDEO_SUMMARY_SUCCESS = "RESET_VIDEO_SUMMARY_SUCCESS";
export const RESET_VIDEO_SUMMARY_FAILURE = "RESET_VIDEO_SUMMARY_FAILURE";

// audios
export const LOADING_AUDIOS = "LOADING_AUDIOS";
export const LOAD_AUDIOS_SUCCESS = "LOAD_AUDIOS_SUCCESS";
export const LOAD_AUDIOS_FAILURE = "LOAD_AUDIOS_FAILURE";
export const CREATING_AUDIO = "CREATING_AUDIO";
export const CREATE_AUDIO_SUCCESS = "CREATE_AUDIO_SUCCESS";
export const CREATE_AUDIO_FAILURE = "CREATE_AUDIO_FAILURE";
export const UPDATE_AUDIO_SUCCESS = "UPDATE_AUDIO_SUCCESS";
export const UPDATE_AUDIO_FAILURE = "UPDATE_AUDIO_FAILURE";
export const DELETING_AUDIOS = "DELETING_AUDIOS";
export const DELETE_AUDIO_SUCCESS = "DELETE_AUDIO_SUCCESS";
export const DELETE_AUDIO_FAILURE = "DELETE_AUDIO_FAILURE";
export const CHANGE_AUDIO_SUMMARY_SUCCESS = "CHANGE_AUDIO_SUMMARY_SUCCESS";
export const CHANGE_AUDIO_SUMMARY_FAILURE = "CHANGE_AUDIO_SUMMARY_FAILURE";
export const RESET_AUDIO_SUMMARY_SUCCESS = "RESET_AUDIO_SUMMARY_SUCCESS";
export const RESET_AUDIO_SUMMARY_FAILURE = "RESET_AUDIO_SUMMARY_FAILURE";

// transcription
export const TRANSCRIBE_SUCCESS = "TRANSCRIBE_SUCCESS";
export const TRANSCRIBE_FAILURE = "TRANSCRIBE_FAILURE";

// summary
export const SUMMARIZE_SUCCESS = "SUMMARIZE_SUCCESS";
export const SUMMARIZE_FAILURE = "SUMMARIZE_FAILURE";

// player
export const PLAYER_SEEKING = "PLAYER_SEEKING";

//pop quiz generation
export const QuizGen_SUCCESS = "QuizGen_SUCCESS";
export const QuizGen_FAILURE = "QuizGen_FAILURE";
export const RESET_AUDIO_QUIZ_SUCCESS = "RESET_AUDIO_QUIZ_SUCCESS";
export const RESET_AUDIO_QUIZ_FAILURE = "RESET_AUDIO_QUIZ_FAILURE";
export const RESET_VIDEO_QUIZ_SUCCESS = "RESET_VIDEO_QUIZ_SUCCESS";
export const RESET_VIDEO_QUIZ_FAILURE = "RESET_VIDEO_QUIZ_FAILURE";

//Text
export const CREATING_TEXT = "CREATING_TEXT";
export const CREATE_TEXT_SUCCESS = "CREATE_TEXT_SUCCESS";
export const CREATE_TEXT_FAILURE = "CREATE_TEXT_FAILURE";
export const LOADING_TEXTS = "LOADING_TEXTS";
export const LOAD_TEXTS_SUCCESS = "LOAD_TEXTS_SUCCESS";
export const LOAD_TEXTS_FAILURE = "LOAD_TEXTS_FAILURE";
export const UPDATE_TEXT_SUCCESS = "UPDATE_TEXT_SUCCESS";
export const UPDATE_TEXT_FAILURE = "UPDATE_TEXT_FAILURE";
export const RESET_TEXT_QUIZ_SUCCESS = "RESET_TEXT_QUIZ_SUCCESS";
export const RESET_TEXT_QUIZ_FAILURE = "RESET_TEXT_QUIZ_FAILURE";


