# Generated by Django 3.1.12 on 2021-06-05 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_login', '0003_auto_20210601_0013'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
